export const carouselText = (delay) =>{
 return{
    hidden:{
        opacity:0,
        x:-100,  
    },
    visible:{
        opacity:1,
        x:0,
        transition:{
            duration:1,
            delay:delay
        }
    }
 }
}
export const navText = (delay) =>{
    return{
       hidden:{
           opacity:0,
           y:-100,  
       },
       visible:{
           opacity:1,
           y:0,
           transition:{
               duration:1,
               delay:delay
           }
       }
    }
   }
export const cardLeft = (delay) =>{
    return{
       hidden:{
           opacity:0,
           x:40,  
       },
       visible:{
           opacity:1,
           x:0,
           transition:{
               duration:1,
               delay:delay
           }
       }
    }
   }
   export const about = (delay) =>{
    return{
       hidden:{
           opacity:0,
           y:100,  
       },
       visible:{
           opacity:1,
           y:0,
           transition:{
               duration:1,
               delay:delay
           }
       }
    }
   }
   export const footer = (delay) =>{
    return{
       hidden:{
           opacity:0,
           y:100,  
       },
       visible:{
           opacity:1,
           y:0,
           transition:{
               duration:1,
               delay:delay
           }
       }
    }
   }
   export const price = (delay) =>{
    return{
       hidden:{
           opacity:0,
           x:-70,  
       },
       visible:{
           opacity:1,
           x:0,
           transition:{
               duration:1,
               delay:delay
           }
       }
    }
   }